create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_conversation_idx
  on public.chat_messages (user_id, conversation_id, created_at);

create table if not exists public.chat_memories (
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null,
  summary jsonb not null default '{"userProfile":"","goals":[],"preferences":[],"importantFacts":[],"openQuestions":[]}'::jsonb,
  recent_messages jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, conversation_id)
);

alter table public.chat_messages enable row level security;
alter table public.chat_memories enable row level security;

create policy "Users can manage their own chat messages"
  on public.chat_messages for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can manage their own chat memories"
  on public.chat_memories for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);